name: BuildCI

on: [push, pull_request]

jobs:
  # Uncomment for a while, since native aarch64 build(on qemu) requires 2 hour+ for compiling
  # build-native-aarch64:

  #   runs-on: ubuntu-18.04
  #   name: Build on native aarch64

  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: uraimo/run-on-arch-action@v1.0.5
  #     id: aarch64-build-on-qemu-aarch64
  #     with:
  #       architecture: aarch64
  #       distribution: ubuntu18.04
  #       run: |
  #         apt-get update
  #         apt-get install -y cmake gcc g++
  #         ./scripts/bootstrap-aarch64-linux.sh
  #         cd build-aarch64
  #         make VERBOSE=1

  build-cross-aarch64:

    runs-on: ubuntu-18.04
    name: Build on cross aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: CmakeAndBuild
        run: |
            apt-get update
            apt-get install -y build-essential
            apt-get install -y gcc-8-aarch64-linux-gnu g++-8-aarch64-linux-gnu
            ./scripts/bootstrap-aarch64-gcc-cross-linux.sh
            cd build-aarch64-cross
            make VERBOSE=1
