name: C/C++ CI

on: [push]

jobs:
  build-aarch64:

    runs-on: ubuntu-18.04
    name: Build on aarch64

    steps:
    - uses: actions/checkout@v1
    - uses: uraimo/run-on-arch-action@v1.0.5
      id: aarch64-build
      with:
        architecture: aarch64
        distribution: ubuntu18.04
        run: |
          sudo apt-get install -y build-essential
          ./scripts/bootstrap-aarch64-linux.sh
          cd build
          make
